env:
  browser: true
  commonjs: true
  es2021: true
  es6: true
  node: true
extends:
  - google
  - prettier
parserOptions:
  ecmaVersion: 13
rules: {
      'prettier/prettier': 'error',
      'max-len': 2,
      'no-undef': 2,
      'valid-jsdoc': 2,
      'no-script-url': 2,
      'no-var': 2,
      
}
plugins: [prettier]